# Generated by Django 4.1.5 on 2023-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_images",
            name="uploadto",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="car_images",
            name="images",
            field=models.ImageField(
                upload_to=models.CharField(default="", max_length=25)
            ),
        ),
    ]
