# Generated by Django 4.1.5 on 2023-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_images_uploadto_alter_car_images_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car_images",
            name="uploadto",
        ),
        migrations.AlterField(
            model_name="car_images",
            name="images",
            field=models.ImageField(upload_to="cars/images"),
        ),
    ]
