# Generated by Django 4.1.5 on 2023-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_car_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
