# Generated by Django 4.1.5 on 2023-01-21 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="book_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="return_b",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="return_date",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
