# Generated by Django 4.1.5 on 2023-01-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_book_date_order_return_b_order_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="return_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
