# Generated by Django 4.1.5 on 2023-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
