# Generated by Django 4.1.5 on 2023-01-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price_per_day",
            field=models.IntegerField(default=0),
        ),
    ]
