# Generated by Django 4.1.5 on 2023-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_price_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_b",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CancelOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancel_date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
